### ISSUE TITLE
Prepare links and icons to add at the home page.

### ISSUE THREAD

**Issue by otaviojava** [JNOSQL/jnosql.github.io#17]
At the email list, we're discussing the specification, thereby we gonna have javadoc, specification as pdf and HTML soon. I need to prepare the site to have these links information in the site.

**Comment by andresgalante** [comment]
I am a bit lost about this issue. What exactly should I add? is it a link on the navigation? or is it a couple of btns on the docs that leads to another page or a PDf dwnload?

**Comment by otaviojava** [comment]
We gonna have three links:

1) The first one will be a link to download a PDF
2) A link to an HTML document like this https://docs.jboss.org/weld/reference/latest/en-US/html/events.html
3) A link to Java doc

I don't know who can we put it on the site if a link or just a menu item will fit better.

**Comment by dearrudam** [comment]
@otaviojava, is it solved?

**Comment by otaviojava** [comment]
Yes, thanks
