### ISSUE TITLE
Update link to examples/demos

### ISSUE THREAD

**Issue by keilw** [JNOSQL/jnosql.github.io#30]
In the http://www.jnosql.org/getting_started.html#references the link should change to:
"https://github.com/JNOSQL?q=demo+OR+endgame&type=&language="
and the label may change to "Sample code" although the plural isn't exactly wrong.

**Comment by dearrudam** [comment]
It was fixed on this commit: https://github.com/JNOSQL/jnosql.github.io/commit/c11c8c71454d9d5a279cf6a34a7bff4a03818f2b
