### ISSUE TITLE
Help : How to provide MongoCredentials to createMongoDbDocumentConfiguration

### ISSUE THREAD

**Issue by genxlogics** [JNOSQL/jnosql.github.io#33]
I see the example only shows the mongodb-host property. I wanted to know how to include the mongo credentials to create Configuration object.

**Comment by dearrudam** [comment]
@genxlogics, you can define the database settings using the [MicroProfile Config](https://microprofile.io/microprofile-config/) specification, so you can add properties and overwrite it in the environment following the [Twelve-Factor App](https://12factor.net/config).

For your scenario, you can define the Mongo credentials in the `microprofile-config.properties`:

```properties
jnosql.mongodb.user=??? # The user’s userID.
jnosql.mongodb.password=??? # The user’s password
jnosql.mongodb.authentication.source=??? # The source where the user is defined.
jnosql.mongodb.authentication.mechanism=??? # Authentication mechanisms com.mongodb.AuthenticationMechanism
```
Or by defining the environment variables like:
``` env
JNOSQL_MONGODB_USER=???
JNOSQL_MONGODB_PASSWORD=???
JNOSQL_MONGODB_AUTHENTICATION_SOURCE=???
JNOSQL_MONGODB_AUTHENTICATION_MECHANISM=???
```
For more info: https://github.com/eclipse/jnosql-databases#configuration-10
