### ISSUE TITLE
Update website to be compliant with the JNoSQL 1.0.0 version 

### ISSUE THREAD

**Issue by dearrudam** [JNOSQL/jnosql.github.io#66]
It's needed to update the website to be compliant with the JNoSQL 1.0.0 version. Some tasks to do:

- Update all dependencies to point to the latest JNoSQL 1.0.0 version;
- Update the `10. Eclipse MicroProfile Config` in order to be compliant with the JNoSQL 1.0.0 version;
- Add information about the sample codes;
- Add information about how to contribute to the project;

**Comment by otaviojava** [comment]
Thank you, @dearrudam could you check it now?

**Comment by dearrudam** [comment]
@otaviojava LGTM!!! Thanks so much!!! Maybe we could add some pages showing or pointing to the sample codes!!

**Comment by otaviojava** [comment]
Yes, I would love to.
